<?php

/**
 * Created by PhpStorm.
 * User: user
 * Date: 19.11.2017
 * Time: 18:30
 */
class CallbackController extends BaseController
{
    /** @var $admin BotEntity  */
    private $bot   = null;

    public function init()
    {
        $this->bot = new BotEntity();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function actionVk()
    {
        $data = json_decode(file_get_contents('php://input'));

        if ($data->type == 'board_post_new'
            && $data->secret == Globals::$config->group_secret
            && $data->object->from_id != ('-' . Globals::$config->group_id)
        ) {
            $userModel = new UserModel();
            $userEntity = $userModel->findBySocialId($data->object->from_id);
            $model = new ActionModel();
            $data = $model->getScores($userEntity->id);

            $message = "[id$userEntity->id|$userEntity->name], ваши очки:\n"
                . " - за лайки постов - {$data['like']['scores']}\n"
                . " - за лайки в числе первых - {$data['ten_like']['scores']}\n"
                . " - за первый лайк - {$data['first_like']['scores']}\n"
                . " - за коментарии постов - {$data['comment']['scores']}\n"
                . " - за репосты - {$data['repost']['scores']}\n";
            VkSdk::addComment(Globals::$config->standalone_token, $message);

            echo 'ok';
            exit();
        } else {
            echo Globals::$config->group_confirm;
            exit();
        }
    }
}